### ISSUE TITLE
Optimize main loop

### ISSUE THREAD

**Issue by midzer** [JoseTomasTocino/freegemas#41]
Hi,

Great game! :)  Because I like it so much, I was working on a web port of Freegemas.

On the go, I've optimized main loop to lower CPU usage to better support older mobile devices.

In addition, proper scaling for all resolutions with `SDL_RenderSetLogicalSize()`, no more manual recalcing of mouse position on resize any more!

For the native game, relevant changes are mainly in `go_window` files

https://github.com/JoseTomasTocino/freegemas/compare/master...midzer:freegemas:emscripten

Let's talk about this. If you're interested, I can create a new branch and pick those changes for a PR.

Have a nice week
midzer

**Comment by sharkwouter** [comment]
Hey @midzer, thanks for reporting this! I wouldn't mind it running a bit faster, but it would be nice to keep the ability to resize the window and the game to fill it. How much of a difference does each of your changes make?

What's missing for me to be able to just merge your work here would be that I don't really understand the changes in the `CMakeLists.txt` file and that the main is now Emscripten specific and will not compile for other systems anymore.

**Comment by midzer** [comment]
Hi @sharkwouter and thanks for your reply :)

I would pick relevant changed lines manually (without Emscripten) in a separate branch and open a PR.

Then we can check together.

**Comment by sharkwouter** [comment]
That's cool with me. I do think it would be good to have the web port in this repo in the end as well, though.

**Comment by midzer** [comment]
Yes, let's investate a proper way to integrate it afterwards.

**Comment by midzer** [comment]
Let's close this one for good and discuss further changes regarding the web port in another issue.

**Comment by sharkwouter** [comment]
Cool, thanks for the contribution!
